### ISSUE TITLE
TYPO3 11: Images will not be generated

### ISSUE THREAD

**Issue by Gernott** [netresearch/t3x-rte_ckeditor_image#144]
I use TYPO3 11.5.3 with rte_ckeditor_image from the master branch here.
It works fine, but there is one issue:
When you delete the files in fileadmin/_processed_/ in the Installtool -> Maintenance -> Remove Temporary Assets, then the Images in the RTE will not be generated again. In the Frontend you get an 404 on all Images from the RTE.
To get the Images again, you have to open every RTE with an Image in the Backend, wait until the Images are loaded (yes, here it works), and save.

**Comment by spfeifer** [comment]
Hi,
I just stumbled upon the same issue after updating a system to TYPO3 11.5 and the extension to 11.0.2.
It was fixed by including the typoscript setup of the extension as described here: https://github.com/netresearch/t3x-rte_ckeditor_image/issues/158#issuecomment-1081822509 ("You have to include the static template before the Fluid Styled content template.")

**Comment by Gitsko** [comment]
Hi, 
i updated the readme for typoscript setup to prevent the problem.
