### ISSUE TITLE
Typo3 11 Update Refindex fails

### ISSUE THREAD

**Issue by LMFC-Krisi** [netresearch/t3x-rte_ckeditor_image#157]
Hello 
Since I Install ckeditor_image 11.0.2 in Typo3 11.5.7 the Update of my Database Refindex fails with following Error.

> (1/1) #1320286857 TYPO3\CMS\Core\Resource\Exception\InvalidPathException
File /<h4>&nbsp;</h4> <p is not valid (".." and "//" is not allowed in path).
in /homepages/33/d13475450/htdocs/typo3_src-11.5.7/typo3/sysext/core/Classes/Resource/Driver/AbstractHierarchicalFilesystemDriver.php line 53"

`    // filePath must be valid
        // Special case is required by vfsStream in Unit Test context
        if (!$this->isPathValid($filePath) && strpos($filePath, 'vfs://') !== 0) {
            throw new InvalidPathException('File ' . $filePath . ' is not valid (".." and "//" is not allowed in path).', 1320286857);
        }
        return $filePath;
    }`
This is not the whole Error Message because it goes over many sites. 
I hope anybody has an idea what is wrong.
Regards Michael

**Comment by saitho** [comment]
Same issue when using the `Ext:linkvalidator`.

I refactored my local version of `Classes/Database/RteImagesSoftReferenceIndex.php` to use `execute` instead of `findRef`.
`findRef` is deprecated in v11 and marked as internal as well.
At least the error is gone – but I haven't checked if the result is fine.
