### ISSUE TITLE
Typo3 12.4.1 extension not working

### ISSUE THREAD

**Issue by Qrecki** [netresearch/t3x-rte_ckeditor_image#262]
I try to run extension on Typo3 12.4.1, Extenstion installed from TER, configuration prepared in accordance with the documentation, but i can't still add an image in ckeditor.

 - TYPO3 version: 12.4.1
 - PHP version: 8.2.7
 - Extension version: 12.0.0

**Comment by yodaXX** [comment]
@Qrecki Idk, what exactly your issue is, but i had to deal with issues in Typo3 v12.4.9 myself.
I use a custom RTE preset.
In order to make the Toolbar Item show up in Backend, I had to insert the item "insertimage".
And for the Frontend rendering I had to include the extensions static Typoscript **after** fluid_styled_content

**Comment by Qrecki** [comment]
@yodaXX Thank you for help.
I was inserting wrong item, I tried "image" not "insertimage". Now looks the extension working correctly.
